### ISSUE TITLE
Tiles placed do not match terrain peering bits

### ISSUE THREAD

**Issue by alex-osborn** [dandeliondino/tile_bit_tools#57]
Hi, great work with the addon. I'm reporting this here in case you have any insight, but suspect this is possibly just another bug with the Godot 4 terrain algorithm.

![Screenshot 2023-04-25 at 6 00 19 PM](https://user-images.githubusercontent.com/880420/234187451-3f9373d5-c6f5-46ea-bf97-b4bdfe623a1c.png)

Issue: After applying the Wang (Tilesetter) and Wang 3-Terrain transition (Tilesetter), actually using the tilemap places tiles connected to the wrong terrains.

Steps I followed:
- Set up new Tilemap + Tileset
- Add new Atlas tiles
- Create a grass center tile using fill
- Apply 3x wang templates
- Apply 1x 3-Terrain transition template
- Start recording video

You'll see that the transitions don't apply correctly, indeed in the last few seconds are the clearest example: tiles marked with the grass terrain are appearing even when fully surrounded by two other terrains.

https://user-images.githubusercontent.com/880420/234188479-f6a3e627-a59a-4e5b-adad-8c46dde42b45.mp4

**Comment by dandeliondino** [comment]
This was an interesting one and it gave me an excuse to use the [Terrain Debugger plugin](https://github.com/dandeliondino/terrain-debugger) to figure it out. Unlike many other problems I've been running into lately, it turns out the algorithm was actually behaving as expected here, which means there is a solution (it's at the end). I think this should be added somewhere in the TileBitTools documentation, so thank you very much for bringing it to my attention!

Looking at the last few seconds, my first thought was that perhaps it was because the grass terrain was listed first and it was trying to use it as a transition. I believe I managed to replicate your setup (including the same problem at the end), and I was wrong (... and that's why I made the debugger plugin in the first place).

![debugger_01](https://user-images.githubusercontent.com/68911895/234466689-7033d622-942a-45f5-874a-9aceab69785d.png)

I opened up the first tile the algorithm selected (0). The snapshot on the left shows that the algorithm took into account the existing pink tiles and the newly-painted yellow tiles, and was looking for the correct tile, prioritizing the yellow center and top-left corner bits over matching the pink corners.

But when it scored the tiles (higher score = worse match), it didn't find a perfect score of 0. The closest it got was 1.

Scrolling down Scored Tiles, the tile it should have picked has a score of 10, meaning the center bit didn't match. And, indeed, the center bit for that tile is pink in my setup (probably 'path' in yours?)

![debugger_01_scored](https://user-images.githubusercontent.com/68911895/234466783-847d88d2-4d91-4401-a2ea-f1bce0de4cc8.png)

So the terrain algorithm was correct, even if annoyingly so. I tried creating a second source with the same texture, and swapping the center bits for the yellow/pink tiles and it fixes the problem at the end, as well as the problem at 0:49.

However, there's another question. Starting around 0:40, drawing path towards dirt (pink to yellow in my screenshots), creates grass transition tiles, while drawing dirt towards path (yellow to pink in my screenshots) tries to join the two together.

![debugger_02](https://user-images.githubusercontent.com/68911895/234466805-8b3ac15a-8a42-45eb-a1ec-5b4a605e49b8.png)

In this screenshot, the problem starts at tile 24. And, again, the algorithm is looking for an appropriate tile. But all the 3-terrain transitions have yellow center bits. It prioritizes the center bit = painted terrain, and I painted pink.

Doing the same trick of duplicating the sources and assigning the transition tiles to pink center bits fixes this, and now painting pink will join to yellow. I did the same thing for green, and I'm able to paint every terrain on top of every other one with expected results.

![solution](https://user-images.githubusercontent.com/68911895/234466658-8b77f619-bf1b-462b-a4b4-21911f5b672d.png)

I think this is probably a viable workaround. It's a bit of work, but fairly quick with TileBitTools (using the templates, then Set Bits to change the center bits). I don't think having multiple sources will have too much impact on performance in-game since they use the same texture, though having extra terrain tiles could slow down terrain painting in the editor.

Let me know whether this fixes all the problems or if there are others.

**Comment by alex-osborn** [comment]
Hi. Thanks for the detailed comment and time you spent on this.

The debugger plugins looks very insightful. Looks like you're correct regarding the tilesets requiring multiple sources. I had been stumbling towards a similar conclusion but wasn't there yet after swapping the centre bits back and forth during testing, thinking I had them set incorrectly - but had no confirmation the configuration was correct.

This seems to be the biggest issue with the Godot 4 tilesets in my opinion - a lack of clear use cases and documentation providing working examples.

I'll have more time later this week to confirm if everything works correctly for me with the solution above. I suspect there may be an issue though, but due to my use case.

Specifically: I am planning to use the tileset bitmasking functionality with procedurally generated maps, so no hand-painting in the editor.

Ideally, the process will run similar to:
- Run a generation process, one of the outputs of which will be a tilemap. At this point the tiles should be assigned to a terrain but we don't care about autotiling yet
- Apply the bitmasking to the whole tilemap, to apply autotiles and join terrains

So I'm not sure the solution above works - because with the duplicated sources, there are multiple ways to get the same tile, depending on which terrain it is.

I will try doing multiple passes to connect the terrains in order? I think this might be required because there is a pretty major functional regression with the v4 tilemap in that you cannot ask for autotiling across multiple terrains at once - you can only apply one terrain at a time, unless I have misunderstood something.

e.g. Godot 4 [set_cells_terrain_connect](https://docs.godotengine.org/en/stable/classes/class_tilemap.html#class-tilemap-method-set-cells-terrain-connect)

vs. Godot 4 [update_bitmask_region](https://docs.godotengine.org/en/3.4/classes/class_tilemap.html?highlight=tilemap#class-tilemap-method-update-bitmask-region)

**Comment by dandeliondino** [comment]
Yeah, I am actually in a similar position in trying to make tiles work for proc gen, and that was really why I made the terrain debugger. (And why I was excited to see your initial problem had an actual solution — because most of what I’m running into on that front doesn’t seem to.)

Since the algorithm is deterministic, I thought if I just understood how it worked I’d be able to figure out a way to set up the tilesets and scripted terrain painting in a way that would work reliably, including order of terrains to paint.

But, from what I can tell after doing a deep dive into the mechanics with the debugger, there are two major blockers for this — the algorithm is not taking enough data from surrounding tiles into account, and it’s not doing any backtracking, either of already-placed tiles or of the tiles in a single update. It’s missing anything even close to that bitmask update function from Godot 3, like you pointed out. And so it seems to be setting itself up to blindly choose non-matching tiles from time to time, and, even when a matching tile exists, it can’t fix its mistake. 

Unfortunately, it’s been stated this is a “won’t fix” in the core engine. So, the best solution I can come up with is to write a script to find and fix non-matching tiles after tiles are placed. (Essentially emulate what users have to do in the editor.) But, by that point, you have enough logic to create your own algorithm.

I’m not at the point where I have to decide right now, but when I get there I think I will either be doing that or using a plugin like Better Terrain.

**Comment by alex-osborn** [comment]
Sounds frustrating. Agree with all your comments.

I set up an isolated reproduction of that issue and added an issue to the main Godot repo for reference:

https://github.com/godotengine/godot/issues/76493

Came across Better Terrain also - had some success and the approach makes more sense to me. Ran into workflow issues though which are exactly the thing TileBitTools solves (applying from templates, building templates to apply).

**Comment by dandeliondino** [comment]
Oh I thought this issue was actually an example of the algorithm behaving as expected? In your example, the algorithm would have had to alter the painted terrain of the cell in order to find a matching tile, and keeping the painted center bits the same are pretty important for proc gen. Unless you’re asking for a different solution?
